on:
  push:
    tags:
      - 'v[0-9]+.*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release

jobs:
  create_release:
    name: Create draft release
    if: >
      github.repository_owner == 'input-output-hk'
      || startsWith(github.event.head_commit.message, 'TEST CI:')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Get version from tag name
        id: version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        run: |
          release_tag=${GITHUB_REF#refs/tags/}
          hub release create --draft \
            -m "Release ${{ steps.version.outputs.version }} (in progress)" \
            $release_tag
